<?php
/**
 * @file
 * This is the file description for form custom ('POSTOBON').
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly.
 *
 * @author Juan David Ceballos ('Developer Web Semi senior('Drupal')')
 */

/**************************************************************************************************************************************** "Welcome Hooks" **********************************************
***************************************************************************************************/

/**
 * Implementation of hook_menu().
 */

function newsletter_menu() {
  $items = array();
  $items['admin/structure/load_newsletters'] = array(
  'title' => 'Newsletter',
  'description' => 'Formulario de Carga de Datos.',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('newsletter_form'),
  'access arguments' => array('newslatter_permission'),
  'type' => MENU_NORMAL_ITEM, 
  );

  $items['admin/structure/view_newsletter'] = array(
  'title' => 'Vista Newsletter', 
  'description' => 'Vista infografias de datos Newsletter', 
  'page callback' => '_newsletter_main_table_custom', 
  'page arguments' => '',
  'access callback' => TRUE,
  'type' => MENU_NORMAL_ITEM, 
  );  
  return $items;
}
/*
 * Implements hook_form().
 */
function newsletter_form($form, &$form_state) {
  $id = 'chekout-wrapper-ms';
  $form['#prefix'] = '<div id="' . $id . '">';
  $form['#suffix'] = '</div>';

  //Initiation Form Billing.
  if (!isset($form_state['storage']['billing'])) {
    $form['first_set']['first'] = array(
      '#type' => 'textfield',
      '#title' => t('name all'),
      '#size' => 30,
      '#attributes' => array('placeholder' => t('Juan David')),
      '#required' => TRUE,
      '#description' => t('Example :Juan david'),
      );

    $form['first_set']['first_c'] = array(
      '#type' => 'textfield',
      '#title' => t('last name'),
      '#size' => 30,
      '#attributes' => array('placeholder' => t('Ceballos Bermudez')),
      '#required' => TRUE,
      '#description' => t('Example :Ceballos Bermudez'),
      );

    $form['first_set']['first_a'] = array(
      '#type' => 'select',
      '#title' => t('gender'),
      '#required' => TRUE,
      '#description' => t('Example :Men or Women'),
      '#options' => array(
        1 => t('Masculino'),
        2 => t('Femenino'),
        ),
      );
    
    $form['first_set']['first_b'] = array(
      '#type' => 'date',
      '#title' => t('date of birth'),
      '#size' => 30,
      '#required' => TRUE,
      '#description' => t('Example :18-12-1993'),
      );

    $form['first_set']['save_fs'] = array(
      '#type' => 'button',
      '#value' => t('Next'),
      '#name' => 'save_billing',
      '#ajax' => array(
        'wrapper' => $id,
        'callback' => 'newsletter_form_ajax',
        ),
      '#attributes' => array(
        'class' => array('btn-success')
        ),
      '#submit' => array('newsletter_form_submit'),
      '#validate' => array('newsletter_form_validate'),
      );
  }

  //Initiation Form Shipping.
  if (isset($form_state['storage']['shipping']['access']) && $form_state['storage']['shipping']['access'] === TRUE) {

  $ciudades = db_select('ciudades', 'it') 
    ->fields('it', array( 'citys')) 
    ->execute() 
    ->fetchAll(); 

  foreach ($ciudades as $key => $value) {
    $citys[] = $value->citys;
  }

    $form['second_set']['second'] = array(
      '#type' => 'select',
      '#title' => t('city'),
      '#required' => TRUE,
      '#description' => t('Example :Bogota'),
      '#options' => $citys,
      );

    $form['second_set']['second_a'] = array(
      '#type' => 'textfield',
      '#title' => t('Movil'),
      '#size' => 30,
      '#required' => TRUE,
      '#attributes' => array('placeholder' => t('3209061118')),
      '#required' => TRUE,
      '#description' => t('Example : 0313333722'),
      );

    $form['second_set']['second_b'] = array(
     '#type' => 'textfield',
     '#title' => t('address'),
     '#size' => 30,
     '#required' => TRUE,
     '#attributes' => array('placeholder' => t('Cra 9 Este#9B-84 Sur')),
     '#description' => t('Example :Cra 9 Este#9B-84-SUR'),
     );

    $form['second_set']['second_btn'] = array(
      '#type' => 'button',
      '#value' => t('Next'),
      '#name' => 'save_shipping',
      '#ajax' => array(
        'wrapper' => $id,
        'callback' => 'newsletter_form_ajax',
        ),
      '#attributes' => array(
        'class' => array('btn-info')
        ),
      '#submit' => array('newsletter_form_submit'),
      '#validate' => array('newsletter_form_validate'),
      );
  }

  //Initiation Form Shipping Rates.

  if (isset($form_state['storage']['shipping_rates']['access']) && $form_state['storage']['shipping_rates']['access'] === TRUE) {
    $form['third_set']['third'] = array(
      '#title' => t('Accept terms and conditions'),
      '#type' => 'checkbox',
      '#size' => 30,
      '#required' => TRUE,
      '#attributes' => array('placeholder' => t('views information')),
      '#required' => TRUE,
      );
    $form['third_set']['third_btn'] = array(
      '#type' => 'button',
      '#required' => TRUE,
      '#value' => t('Next'),
      '#name' => 'save_shipping_rates',
      '#ajax' => array(
        'wrapper' => $id,
       // 'callback' => 'newsletter_form_ajax',
        ),
      '#attributes' => array(
        'class' => array('btn-success-third')
        ),
      '#submit' => array('newsletter_form_submit'),
      '#validate' => array('newsletter_form_validate'),
      );
  }
  drupal_add_js(drupal_get_path('module', 'newsletter') .'/js/validate.js');
  return $form;
}

/*
 * Implements hook_permission().
 */

function newsletter_permission() {
  return array('newslatter_permission' => array('title' => t('Administrate module of newslatter'),
  'restrict access' => true,
   ),
   );
}
/*
 * Implements hook_validate().
 */

function newsletter_form_validate($form, &$form_state) {

 switch ($form_state['clicked_button']['#name']) {

  case 'save_billing':
    $form_state['storage']['billing'] = $form_state['values'];
    $form_state['storage']['billing']['access'] = TRUE;
    $form_state['storage']['shipping']['access'] = TRUE;
    break;


  case 'save_shipping':
    $form_state['storage']['shipping'] = $form_state['values'];
    $form_state['storage']['shipping']['access'] = FALSE;
    $form_state['storage']['shipping_rates']['access'] = TRUE;
   break;

  case 'save_shipping_rates':
   $form_state['storage']['shipping_rates'] = $form_state['values'];
    _insert_database($form, $form_state);
   break;

  }
}

/*
 *Implements Hook Submit
 */
function newsletter_form_submit($form, &$form_state) {
 $form_state['rebuild'] = TRUE;
}


/******************************************************************************************************************************************** "End Hooks" **********************************************
***************************************************************************************************/


/****************************************************************************************************************************************** "Welcome Functions *****************************************
***************************************************************************************************/

/*
 *Implements Function custom for views table with conexion for database.
 */

function _newsletter_main_table_custom() {  
  $header_table_edit = array(
    array('data' => t('id')),  
    array('data' => t('name')),
    array('data' => t('lastname')),
    array('data' => t('gender')),
    array('data' => t('date')),
    array('data' => t('movil')),
    array('data' => t('city')),
    array('data' => t('address')),
  ); 
  $query = db_select('newsletter', 'it') 
    ->fields('it', array('id', 'name_people', 'lastname_people', 'gender' , 'date' 
      , 'number_movil',  'city', 'address')) 
    ->execute() 
    ->fetchAll();  

  foreach ($query as $record_edit_table) {
    $rows_table_edit[] =  
      array(  
        array(   
          'data' => $record_edit_table->id,
        ),
        array(  
           'data' => $record_edit_table->name_people,
        ),
        array(  
           'data' => $record_edit_table->lastname_people,
        ),
        array(  
           'data' => $record_edit_table->gender,
        ),
        array(  
           'data' => $record_edit_table->date,
        ),                
        array(  
           'data' => $record_edit_table->number_movil,
        ),        
        array(  
           'data' => $record_edit_table->city,
        ),        
        array(  
           'data' => $record_edit_table->address,
        ),        
    );
  } 
  $caption_table_edit = t('Table for views information peoples');
  return  theme('table',   
      array( 
              'header' => $header_table_edit,   
              'rows'   => $rows_table_edit,   
              'caption'=> $caption_table_edit 
            ) 
  );  
}


function _insert_database($form, $form_state) {
 $mount = $form_state['storage']['billing']['first_b']['month'];
 $day = $form_state['storage']['billing']['first_b']['day'];
 $year = $form_state['storage']['billing']['first_b']['year'];

 $day_all = $day.'-'.$mount.'-'.$year;
 if ($form_state['storage']['billing']['first_a'] == 2){
    $Genero = 'Femenino';
 }else{
    $Genero = 'Masculino';
 }

 $nid = db_insert('newsletter') -> fields(
    array(
      'name_people' => $form_state['storage']['billing']['first'],
      'lastname_people' => $form_state['storage']['billing']['first_c'],
      'gender' => $Genero,
      'date'   => $day_all,
      'number_movil' => $form_state['storage']['shipping']['second_a'],
      'city' => 'Bogota',
      'address' => $form_state['storage']['shipping']['second_b'], 
    )
  )-> execute();  

  return drupal_goto('admin/structure/view_newsletter');
}

/******************************************************************************************************************************************** "End Hooks" **********************************************
***************************************************************************************************/

/**
  * Implements ajax form.
*/
function newsletter_form_ajax($form, &$form_state, $valor, $key_name, $name_campo) {
  global $error;

  if ($form_state['storage']['shipping'] ['access'] === TRUE) {
     $ajax_one = array(
        '#type' => 'ajax',
        '#commands' => $commands,
      );
  }

  if ($form_state['storage']['shipping_rates']['access'] === TRUE) {
      
      $ajax_two = array(
          '#type' => 'ajax',
          '#commands' => $commands,
          );
  }

  $commands[] = ajax_command_replace('#chekout-wrapper-ms', render($form));

 return  array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

